[phases.setup]
nixPkgs = [
  "python3",
  "gcc",
  "libreoffice",
  "jre",
  "fontconfig",
  "pango",
  "cairo",
  "gobject-introspection",
  "libffi",
  "glib"
]

[start]
cmd = "LD_LIBRARY_PATH=/nix/profile/lib:/app/.nix-profile/lib:/root/.nix-profile/lib uvicorn app:app --host 0.0.0.0 --port 3000"

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "mkdir -p ~/.local/share/fonts",
  "cp fonts/*.ttf ~/.local/share/fonts/ || true",
  "fc-cache -f -v"
]
