[phases.setup]
nixPkgs = ["python3", "gcc", "libreoffice", "jre", "fontconfig"]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "mkdir -p ~/.local/share/fonts",
  "cp fonts/*.ttf ~/.local/share/fonts/ || true",
  "fc-cache -f -v"
]
